name: crud_bloc_gen
description: A package for generating CRUD BLoC code
version: 1.0.0
homepage: https://github.com/yourusername/crud_bloc_gen

environment:
  sdk: ">=3.0.0 <4.0.0" # Updated SDK constraint
  flutter: ">=3.10.0" # Added Flutter SDK constraint

dependencies:
  build: ^2.4.1
  source_gen: ^1.4.0
  analyzer: ^6.2.0
  freezed_annotation: ^2.4.1
  flutter_bloc: ^8.1.3
  fpdart: ^1.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.6 # Updated to latest version
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  flutter_test:
    sdk: flutter
